CREATE TABLE IF NOT EXISTS `admin` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `username` VARCHAR(20) NOT NULL COMMENT '账号',
    `password` VARCHAR(128) NOT NULL COMMENT '密码',
    `realname` VARCHAR(20) NULL COMMENT '真实姓名',
    `email` VARCHAR(200) NULL COMMENT '邮箱',
    `remark` VARCHAR(500) NULL COMMENT '备注',
    `is_superadmin` BOOL DEFAULT FALSE NOT NULL COMMENT '超管账号',
    `is_active` BOOL DEFAULT FALSE NOT NULL COMMENT '账号是否激活',
    `last_login` DATETIME NULL COMMENT '最后登陆时间',
    `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_at` DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE (`username`),
    UNIQUE (`email`)
) ENGINE = InnoDB COMMENT = '管理员表';

CREATE TABLE IF NOT EXISTS `users` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `user_type` TINYINT(1) UNSIGNED NOT NULL COMMENT '用户类型',
    `username` VARCHAR(20) NULL COMMENT '账号',
    `password` VARCHAR(128) NULL COMMENT '密码',
    `email` VARCHAR(200) NULL COMMENT '邮箱',
    `phone` VARCHAR(16) NULL COMMENT '手机号',
    `avatar` VARCHAR(200) NULL COMMENT '头像',
    `is_active` BOOL DEFAULT FALSE NOT NULL COMMENT '账号是否激活',
    `last_login` DATETIME NULL COMMENT '最后登陆时间',
    `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_at` DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE (`username`),
    UNIQUE (`email`),
    UNIQUE (`phone`)
) ENGINE = InnoDB COMMENT = '用户表';

CREATE TABLE IF NOT EXISTS `books` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `name` VARCHAR(20) NOT NULL COMMENT '书名',
    `price` DECIMAL(8, 2) NOT NULL COMMENT '单价',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '作者',
    `type` TINYINT(1) UNSIGNED DEFAULT '1' NOT NULL COMMENT '1纸书，2PDF，3TXT',
    `stock` INT UNSIGNED NOT NULL COMMENT '库存',
    `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_at` DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `user_id` (`user_id`),
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB COMMENT = '书表';

-- ALTER TABLE `books` ADD FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS `posts` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `title` VARCHAR(20) NOT NULL COMMENT '标题',
    `content` VARCHAR(300) NOT NULL COMMENT '内容',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT '发帖人',
    `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_at` DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `user_id` (`user_id`),
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB COMMENT = '帖子表';

CREATE TABLE IF NOT EXISTS `auth_group` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `name` VARCHAR(100) NOT NULL COMMENT '组名',
    `desc` VARCHAR(150) NOT NULL COMMENT '组详情',
    `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_at` DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE (`name`)
) ENGINE = InnoDB COMMENT = '权限组';

CREATE TABLE IF NOT EXISTS `auth_permission` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `name` VARCHAR(100) NOT NULL COMMENT '权限名',
    `desc` VARCHAR(150) NOT NULL COMMENT '权限详情',
    `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_at` DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE (`name`)
) ENGINE = InnoDB COMMENT = '权限';

CREATE TABLE IF NOT EXISTS `m2m_group_permission` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `group_id` BIGINT UNSIGNED NOT NULL,
    `permission_id` BIGINT UNSIGNED NOT NULL,
    `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_at` DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `group_id` (`group_id`),
    KEY `permission_id` (`permission_id`),
    UNIQUE (`group_id`, `permission_id`),
    FOREIGN KEY (`group_id`) REFERENCES `auth_group`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`permission_id`) REFERENCES `auth_permission`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB COMMENT = '权限组-权限';

CREATE TABLE IF NOT EXISTS `m2m_admin_permission` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `admin_id` BIGINT UNSIGNED NOT NULL,
    `permission_id` BIGINT UNSIGNED NOT NULL,
    `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_at` DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `admin_id` (`admin_id`),
    KEY `permission_id` (`permission_id`),
    UNIQUE (`admin_id`, `permission_id`),
    FOREIGN KEY (`admin_id`) REFERENCES `admin`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`permission_id`) REFERENCES `auth_permission`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB COMMENT = '管理员-权限';

CREATE TABLE IF NOT EXISTS `m2m_admin_group` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `admin_id` BIGINT UNSIGNED NOT NULL,
    `group_id` BIGINT UNSIGNED NOT NULL,
    `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_at` DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `admin_id` (`admin_id`),
    KEY `group_id` (`group_id`),
    UNIQUE (`admin_id`, `group_id`),
    FOREIGN KEY (`admin_id`) REFERENCES `admin`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`group_id`) REFERENCES `auth_group`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB COMMENT = '管理员-权限组';

CREATE TABLE IF NOT EXISTS `admin_log` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
    `action_flag` TINYINT(1) UNSIGNED NOT NULL COMMENT '操作事件',
    `action_msg` VARCHAR(100) NOT NULL COMMENT '调用的哪个函数',
    `desc` VARCHAR(200) NOT NULL COMMENT '具体做了什么',
    `admin_id` BIGINT UNSIGNED NOT NULL COMMENT '操作人',
    `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_at` DATETIME ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `admin_id` (`admin_id`),
    FOREIGN KEY (`admin_id`) REFERENCES `admin`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB COMMENT = '管理员操作日志';